# Generated by Django 3.2 on 2021-08-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nebula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='question_text',
        ),
    ]
