# Generated by Django 3.2 on 2021-08-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nebula', '0002_remove_project_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
